version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: org.json:json
    versions:
    - "20201115"
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - 4.9.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
