name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]

# Jobs
jobs:
  codecov-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
             
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip
           
      - name: Run tests and collect coverage
        run: mvn -B test 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: tests
          name: razorpay-java
          fail_ci_if_error: true
          verbose: true
          
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        
      - name: Build with Maven
        run: mvn clean package -B
        
      - name: Publish package
        run: |
            mvn deploy -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
