name: Maven Package

on:
  push:
   branches: [publish_workflow]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

    - name: Build with Maven
      run: mvn -B package --file dev_workflow/pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -f dev_workflow/pom.xml -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
