# This workflow will build a Java project with Maven, run tests with JaCoCo, and analyze the code with SonarCloud
name: Java CI

# Controls when the workflow will run
on:
  push:
    branches: [ test_codecov ]
  pull_request:
    branches: [ test_codecov ]

# Jobs
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: tests
          name: razorpay-java
          fail_ci_if_error: true
          verbose: true
